CREATE TABLE admin (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE,
username VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
active BOOLEAN NOT NULL DEFAULT TRUE
);
